*: upgrade test containers to v0.37.0
Prior to this commit is was quite common to see tests fail due to the following
error:

```
--- FAIL: TestClientPasswordCreation (5.75s)
    client_test.go:132:
                Error:          Received unexpected error:
                                failed to get mapped Kafka port: port not found
                Test:           TestClientPasswordCreation
```

This commit upgrades to the latest version of test containers which appears to
fix these flakes. (On my machine at least).