operator: Include ClusterRole permission for redpanda controller
In the redpanda package the kubebuilder comment does not have all possible
variants of ClusterRole permissions neccessery to handle creation of all
Redpanda helm chart resources. During integration test suite execution
controller runtime complain about leases permissions missing.

```
error: deploying *v1.Role: \"rp-4bpw0i-sidecar-controllers\":
roles.rbac.authorization.k8s.io \"rp-4bpw0i-sidecar-controllers\" is forbidden:
user \"system:serviceaccount:testenv-wm758:testenv-pzy3ce\"
(groups=[\"system:serviceaccounts\" \"system:serviceaccounts:testenv-wm758\" \"system:authenticated\"])
is attempting to grant RBAC permissions not currently held:
{APIGroups:[\"coordination.k8s.io\"], Resources:[\"leases\"], Verbs:[\"create\" \"delete\" \"get\" \"list\" \"patch\" \"update\" \"watch\"]}"
```

The setup of integration test suite included only permissions defined in redpanda package.
Kustomize and Operator helm chart includes those missing permissions.