Fix nightly container build
In the CI the following error poped up when helm chart was pushed to docker hub
container registry:
```
[+] Building 0.0s (0/0)                                          docker:default
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
```

https://buildkite.com/redpanda/redpanda-operator/builds/3741#0193d2e2-385c-4b84-9a23-8b047814b3fe/332-333