operator: Fix missing https port in operator container definition
Fixes error for missing named port https

```
kubectl --namespace redpanda port-forward svc/redpanda-controller-operator-metrics-service 8443:8443
error: Pod 'redpanda-controller-operator-c897f85f9-sprxh' does not have a named port 'https'
```

(cherry picked from commit 59f6af7aeb2d167c2aaa6eb78c190fd614dde7ef)